// <auto-generated />
#nullable enable
using Lettermint.Models;
namespace Lettermint;

public sealed partial class EmailClient : IDisposable
{
    internal Transport Transport { get; }
    internal EmailClient(Transport transport) => Transport = transport;
    public void Dispose() => Transport.Dispose();
    [ApiOperation("sending", "v1.sendMail")]
    public Task<SendEmailResponse> SendAsync(SendMailRequest payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<SendEmailResponse>(HttpMethod.Post, $"/send", payload, options, cancellationToken);

    public Task<SendEmailResponse> SendAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<SendEmailResponse>(HttpMethod.Post, $"/send", payload, options, cancellationToken);

    [ApiOperation("sending", "v1.sendBatchMail")]
    public Task<List<SendBatchEmailResponseItem>> SendBatchAsync(List<SendBatchMailRequestItem> payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<List<SendBatchEmailResponseItem>>(HttpMethod.Post, $"/send/batch", payload, options, cancellationToken);

    public Task<List<SendBatchEmailResponseItem>> SendBatchAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<List<SendBatchEmailResponseItem>>(HttpMethod.Post, $"/send/batch", payload, options, cancellationToken);

    [ApiOperation("sending", "v1.ping")]
    public async Task<string> PingAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => (await Transport.RawAsync(HttpMethod.Get, $"/ping", null, options, cancellationToken).ConfigureAwait(false)).Trim();
}

public sealed partial class DomainsEndpoint
{
    internal Transport Transport { get; }
    internal DomainsEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "domain.index")]
    public Task<DomainIndexResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainIndexResponse>(HttpMethod.Get, $"/domains", null, options, cancellationToken);

    [ApiOperation("team", "domain.store")]
    public Task<DomainData> CreateAsync(StoreDomainData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainData>(HttpMethod.Post, $"/domains", payload, options, cancellationToken);

    public Task<DomainData> CreateAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainData>(HttpMethod.Post, $"/domains", payload, options, cancellationToken);

    [ApiOperation("team", "domain.show")]
    public Task<DomainData> RetrieveAsync(string domainId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainData>(HttpMethod.Get, $"/domains/{Transport.Segment(domainId)}", null, options, cancellationToken);

    [ApiOperation("team", "domain.destroy")]
    public Task<DomainDestroyResponse> DeleteAsync(string domainId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainDestroyResponse>(HttpMethod.Delete, $"/domains/{Transport.Segment(domainId)}", null, options, cancellationToken);

    [ApiOperation("team", "domain.verifyDnsRecords")]
    public Task<DomainVerifyDnsRecordsResponse> VerifyDnsRecordsAsync(string domainId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainVerifyDnsRecordsResponse>(HttpMethod.Post, $"/domains/{Transport.Segment(domainId)}/dns-records/verify", null, options, cancellationToken);

    [ApiOperation("team", "domain.verifySpecificDnsRecord")]
    public Task<DomainVerifySpecificDnsRecordResponse> VerifyDnsRecordAsync(string domainId, string recordId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainVerifySpecificDnsRecordResponse>(HttpMethod.Post, $"/domains/{Transport.Segment(domainId)}/dns-records/{Transport.Segment(recordId)}/verify", null, options, cancellationToken);

    [ApiOperation("team", "domain.updateProjects")]
    public Task<DomainUpdateProjectsResponse> UpdateProjectsAsync(string domainId, UpdateDomainProjectsData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainUpdateProjectsResponse>(HttpMethod.Put, $"/domains/{Transport.Segment(domainId)}/projects", payload, options, cancellationToken);

    public Task<DomainUpdateProjectsResponse> UpdateProjectsAsync(string domainId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<DomainUpdateProjectsResponse>(HttpMethod.Put, $"/domains/{Transport.Segment(domainId)}/projects", payload, options, cancellationToken);
}

public sealed partial class ApiClient : IDisposable
{
    internal Transport Transport { get; }
    internal ApiClient(Transport transport) => Transport = transport;
    public void Dispose() => Transport.Dispose();
    [ApiOperation("team", "v1.ping")]
    public async Task<string> PingAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => (await Transport.RawAsync(HttpMethod.Get, $"/ping", null, options, cancellationToken).ConfigureAwait(false)).Trim();

    [ApiOperation("team", "v1.blockedFileTypes")]
    public Task<V1BlockedFileTypesResponse> BlockedFileTypesAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<V1BlockedFileTypesResponse>(HttpMethod.Get, $"/blocked-file-types", null, options, cancellationToken);
}

public sealed partial class MessagesEndpoint
{
    internal Transport Transport { get; }
    internal MessagesEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "rescheduleMessage")]
    public Task<RescheduleMessageResponse> RescheduleAsync(string messageId, RescheduleMessageRequest payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RescheduleMessageResponse>(HttpMethod.Patch, $"/messages/{Transport.Segment(messageId)}", payload, options, cancellationToken);

    public Task<RescheduleMessageResponse> RescheduleAsync(string messageId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RescheduleMessageResponse>(HttpMethod.Patch, $"/messages/{Transport.Segment(messageId)}", payload, options, cancellationToken);

    [ApiOperation("team", "message.show")]
    public Task<MessageData> RetrieveAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<MessageData>(HttpMethod.Get, $"/messages/{Transport.Segment(messageId)}", null, options, cancellationToken);

    [ApiOperation("team", "cancelScheduledMessage")]
    public Task<CancelScheduledMessageResponse> CancelAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<CancelScheduledMessageResponse>(HttpMethod.Post, $"/messages/{Transport.Segment(messageId)}/cancel", null, options, cancellationToken);

    [ApiOperation("team", "message.index")]
    public Task<MessageIndexResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<MessageIndexResponse>(HttpMethod.Get, $"/messages", null, options, cancellationToken);

    [ApiOperation("team", "message.events")]
    public Task<MessageEventsResponse> EventsAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<MessageEventsResponse>(HttpMethod.Get, $"/messages/{Transport.Segment(messageId)}/events", null, options, cancellationToken);

    [ApiOperation("team", "message.source")]
    public Task<string> SourceAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.RawAsync(HttpMethod.Get, $"/messages/{Transport.Segment(messageId)}/source", null, options, cancellationToken);

    [ApiOperation("team", "message.html")]
    public Task<string> HtmlAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.RawAsync(HttpMethod.Get, $"/messages/{Transport.Segment(messageId)}/html", null, options, cancellationToken);

    [ApiOperation("team", "message.text")]
    public Task<string> TextAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.RawAsync(HttpMethod.Get, $"/messages/{Transport.Segment(messageId)}/text", null, options, cancellationToken);

    [ApiOperation("team", "processInboundMessage")]
    public Task<ProcessInboundMessageResponse> ProcessAsync(string messageId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProcessInboundMessageResponse>(HttpMethod.Post, $"/messages/{Transport.Segment(messageId)}/process", null, options, cancellationToken);
}

public sealed partial class ProjectsEndpoint
{
    internal Transport Transport { get; }
    internal ProjectsEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "project.index")]
    public Task<ProjectIndexResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectIndexResponse>(HttpMethod.Get, $"/projects", null, options, cancellationToken);

    [ApiOperation("team", "project.store")]
    public Task<ProjectStoreResponse> CreateAsync(StoreProjectData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectStoreResponse>(HttpMethod.Post, $"/projects", payload, options, cancellationToken);

    public Task<ProjectStoreResponse> CreateAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectStoreResponse>(HttpMethod.Post, $"/projects", payload, options, cancellationToken);

    [ApiOperation("team", "project.show")]
    public Task<ProjectData> RetrieveAsync(string projectId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectData>(HttpMethod.Get, $"/projects/{Transport.Segment(projectId)}", null, options, cancellationToken);

    [ApiOperation("team", "project.update")]
    public Task<ProjectUpdateResponse> UpdateAsync(string projectId, UpdateProjectData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectUpdateResponse>(HttpMethod.Put, $"/projects/{Transport.Segment(projectId)}", payload, options, cancellationToken);

    public Task<ProjectUpdateResponse> UpdateAsync(string projectId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectUpdateResponse>(HttpMethod.Put, $"/projects/{Transport.Segment(projectId)}", payload, options, cancellationToken);

    [ApiOperation("team", "project.destroy")]
    public Task<ProjectDestroyResponse> DeleteAsync(string projectId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectDestroyResponse>(HttpMethod.Delete, $"/projects/{Transport.Segment(projectId)}", null, options, cancellationToken);

    [ApiOperation("team", "project.rotateToken")]
    public Task<ProjectRotateTokenResponse> RotateTokenAsync(string projectId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<ProjectRotateTokenResponse>(HttpMethod.Post, $"/projects/{Transport.Segment(projectId)}/rotate-token", null, options, cancellationToken);
}

public sealed partial class RoutesEndpoint
{
    internal Transport Transport { get; }
    internal RoutesEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "route.index")]
    public Task<RouteIndexResponse> ListAsync(string projectId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteIndexResponse>(HttpMethod.Get, $"/projects/{Transport.Segment(projectId)}/routes", null, options, cancellationToken);

    [ApiOperation("team", "route.store")]
    public Task<RouteStoreResponse> CreateAsync(string projectId, StoreRouteData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteStoreResponse>(HttpMethod.Post, $"/projects/{Transport.Segment(projectId)}/routes", payload, options, cancellationToken);

    public Task<RouteStoreResponse> CreateAsync(string projectId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteStoreResponse>(HttpMethod.Post, $"/projects/{Transport.Segment(projectId)}/routes", payload, options, cancellationToken);

    [ApiOperation("team", "route.show")]
    public Task<RouteData> RetrieveAsync(string routeId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteData>(HttpMethod.Get, $"/routes/{Transport.Segment(routeId)}", null, options, cancellationToken);

    [ApiOperation("team", "route.update")]
    public Task<RouteUpdateResponse> UpdateAsync(string routeId, UpdateRouteData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteUpdateResponse>(HttpMethod.Put, $"/routes/{Transport.Segment(routeId)}", payload, options, cancellationToken);

    public Task<RouteUpdateResponse> UpdateAsync(string routeId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteUpdateResponse>(HttpMethod.Put, $"/routes/{Transport.Segment(routeId)}", payload, options, cancellationToken);

    [ApiOperation("team", "route.destroy")]
    public Task<RouteDestroyResponse> DeleteAsync(string routeId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteDestroyResponse>(HttpMethod.Delete, $"/routes/{Transport.Segment(routeId)}", null, options, cancellationToken);

    [ApiOperation("team", "route.verifyInboundDomain")]
    public Task<RouteVerifyInboundDomainResponse> VerifyInboundDomainAsync(string routeId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<RouteVerifyInboundDomainResponse>(HttpMethod.Post, $"/routes/{Transport.Segment(routeId)}/verify-inbound-domain", null, options, cancellationToken);
}

public sealed partial class StatsEndpoint
{
    internal Transport Transport { get; }
    internal StatsEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "stats.index")]
    public Task<StatsData> RetrieveAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<StatsData>(HttpMethod.Get, $"/stats", null, options, cancellationToken);
}

public sealed partial class SuppressionsEndpoint
{
    internal Transport Transport { get; }
    internal SuppressionsEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "suppression.index")]
    public Task<SuppressionIndexResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<SuppressionIndexResponse>(HttpMethod.Get, $"/suppressions", null, options, cancellationToken);

    [ApiOperation("team", "suppression.store")]
    public Task<SuppressionStoreResponse> CreateAsync(StoreSuppressionData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<SuppressionStoreResponse>(HttpMethod.Post, $"/suppressions", payload, options, cancellationToken);

    public Task<SuppressionStoreResponse> CreateAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<SuppressionStoreResponse>(HttpMethod.Post, $"/suppressions", payload, options, cancellationToken);

    [ApiOperation("team", "suppression.destroy")]
    public Task<SuppressionDestroyResponse> DeleteAsync(string suppressionId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<SuppressionDestroyResponse>(HttpMethod.Delete, $"/suppressions/{Transport.Segment(suppressionId)}", null, options, cancellationToken);
}

public sealed partial class TeamEndpoint
{
    internal Transport Transport { get; }
    internal TeamEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "team.show")]
    public Task<TeamData> RetrieveAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamData>(HttpMethod.Get, $"/team", null, options, cancellationToken);

    [ApiOperation("team", "team.update")]
    public Task<TeamUpdateResponse> UpdateAsync(UpdateTeamData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamUpdateResponse>(HttpMethod.Put, $"/team", payload, options, cancellationToken);

    public Task<TeamUpdateResponse> UpdateAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamUpdateResponse>(HttpMethod.Put, $"/team", payload, options, cancellationToken);

    [ApiOperation("team", "team.usage")]
    public Task<TeamUsageDetailData> UsageAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamUsageDetailData>(HttpMethod.Get, $"/team/usage", null, options, cancellationToken);

    [ApiOperation("team", "team.roles")]
    public Task<TeamRolesResponse> RolesAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamRolesResponse>(HttpMethod.Get, $"/team/roles", null, options, cancellationToken);

    [ApiOperation("team", "team.members")]
    public Task<TeamMembersResponse> MembersAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamMembersResponse>(HttpMethod.Get, $"/team/members", null, options, cancellationToken);

    [ApiOperation("team", "team.members.show")]
    public Task<TeamMemberData> RetrieveMemberAsync(string userId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamMemberData>(HttpMethod.Get, $"/team/members/{Transport.Segment(userId)}", null, options, cancellationToken);

    [ApiOperation("team", "team.members.assignment.update")]
    public Task<TeamMemberData> UpdateMemberAssignmentAsync(string userId, UpdateTeamMemberAssignmentData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamMemberData>(HttpMethod.Put, $"/team/members/{Transport.Segment(userId)}/assignment", payload, options, cancellationToken);

    public Task<TeamMemberData> UpdateMemberAssignmentAsync(string userId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<TeamMemberData>(HttpMethod.Put, $"/team/members/{Transport.Segment(userId)}/assignment", payload, options, cancellationToken);
}

public sealed partial class WebhooksEndpoint
{
    internal Transport Transport { get; }
    internal WebhooksEndpoint(Transport transport) => Transport = transport;
    [ApiOperation("team", "webhook.index")]
    public Task<WebhookIndexResponse> ListAsync(RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookIndexResponse>(HttpMethod.Get, $"/webhooks", null, options, cancellationToken);

    [ApiOperation("team", "webhook.store")]
    public Task<WebhookStoreResponse> CreateAsync(StoreWebhookData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookStoreResponse>(HttpMethod.Post, $"/webhooks", payload, options, cancellationToken);

    public Task<WebhookStoreResponse> CreateAsync(System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookStoreResponse>(HttpMethod.Post, $"/webhooks", payload, options, cancellationToken);

    [ApiOperation("team", "webhook.show")]
    public Task<WebhookData> RetrieveAsync(string webhookId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookData>(HttpMethod.Get, $"/webhooks/{Transport.Segment(webhookId)}", null, options, cancellationToken);

    [ApiOperation("team", "webhook.update")]
    public Task<WebhookUpdateResponse> UpdateAsync(string webhookId, UpdateWebhookData payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookUpdateResponse>(HttpMethod.Put, $"/webhooks/{Transport.Segment(webhookId)}", payload, options, cancellationToken);

    public Task<WebhookUpdateResponse> UpdateAsync(string webhookId, System.Text.Json.JsonElement payload, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookUpdateResponse>(HttpMethod.Put, $"/webhooks/{Transport.Segment(webhookId)}", payload, options, cancellationToken);

    [ApiOperation("team", "webhook.destroy")]
    public Task<WebhookDestroyResponse> DeleteAsync(string webhookId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookDestroyResponse>(HttpMethod.Delete, $"/webhooks/{Transport.Segment(webhookId)}", null, options, cancellationToken);

    [ApiOperation("team", "webhook.test")]
    public Task<WebhookTestResponse> TestAsync(string webhookId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookTestResponse>(HttpMethod.Post, $"/webhooks/{Transport.Segment(webhookId)}/test", null, options, cancellationToken);

    [ApiOperation("team", "webhook.regenerateSecret")]
    public Task<WebhookRegenerateSecretResponse> RegenerateSecretAsync(string webhookId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookRegenerateSecretResponse>(HttpMethod.Post, $"/webhooks/{Transport.Segment(webhookId)}/regenerate-secret", null, options, cancellationToken);

    [ApiOperation("team", "webhook.deliveries")]
    public Task<WebhookDeliveriesResponse> DeliveriesAsync(string webhookId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookDeliveriesResponse>(HttpMethod.Get, $"/webhooks/{Transport.Segment(webhookId)}/deliveries", null, options, cancellationToken);

    [ApiOperation("team", "webhook.showDelivery")]
    public Task<WebhookDeliveryData> ShowDeliveryAsync(string webhookId, string deliveryId, RequestOptions? options = null, CancellationToken cancellationToken = default)
        => Transport.SendAsync<WebhookDeliveryData>(HttpMethod.Get, $"/webhooks/{Transport.Segment(webhookId)}/deliveries/{Transport.Segment(deliveryId)}", null, options, cancellationToken);
}

public sealed partial class ApiClient
{
    public DomainsEndpoint Domains => new(Transport);
    public MessagesEndpoint Messages => new(Transport);
    public ProjectsEndpoint Projects => new(Transport);
    public RoutesEndpoint Routes => new(Transport);
    public StatsEndpoint Stats => new(Transport);
    public SuppressionsEndpoint Suppressions => new(Transport);
    public TeamEndpoint Team => new(Transport);
    public WebhooksEndpoint Webhooks => new(Transport);
}
