<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PackageId>Lettermint</PackageId>
    <Version>0.1.0</Version>
    <Authors>Lettermint</Authors>
    <Description>The Lettermint SDK for the sending and full APIs.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>lettermint;email;transactional</PackageTags>
  </PropertyGroup>
  <ItemGroup><None Include="../../README.md" Pack="true" PackagePath="/" /></ItemGroup>
</Project>
