// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Lettermint.Models;

[JsonConverter(typeof(WireEnumConverter<AttachmentDelivery>))]
public enum AttachmentDelivery
{
    [EnumMember(Value = "inline")]
    Inline,
    [EnumMember(Value = "url")]
    Url,
}

[JsonConverter(typeof(WireEnumConverter<BuiltInTeamRole>))]
public enum BuiltInTeamRole
{
    [EnumMember(Value = "owner")]
    Owner,
    [EnumMember(Value = "admin")]
    Admin,
    [EnumMember(Value = "member")]
    Member,
}

public sealed class CancelScheduledMessageResponse : ApiModel
{
    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("status")]
    public MessageStatus? Status { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<DkimMode>))]
public enum DkimMode
{
    [EnumMember(Value = "legacy_txt")]
    LegacyTxt,
    [EnumMember(Value = "managed_cname")]
    ManagedCname,
}

[JsonConverter(typeof(WireEnumConverter<DnsRecordPurpose>))]
public enum DnsRecordPurpose
{
    [EnumMember(Value = "return_path")]
    ReturnPath,
    [EnumMember(Value = "dmarc")]
    Dmarc,
    [EnumMember(Value = "dkim_legacy")]
    DkimLegacy,
    [EnumMember(Value = "dkim_primary")]
    DkimPrimary,
    [EnumMember(Value = "dkim_secondary")]
    DkimSecondary,
}

[JsonConverter(typeof(WireEnumConverter<DnsRecordStatus>))]
public enum DnsRecordStatus
{
    [EnumMember(Value = "active")]
    Active,
    [EnumMember(Value = "failed")]
    Failed,
    [EnumMember(Value = "pending")]
    Pending,
}

[JsonConverter(typeof(WireEnumConverter<DnsVerificationScope>))]
public enum DnsVerificationScope
{
    [EnumMember(Value = "required")]
    Required,
    [EnumMember(Value = "recommended")]
    Recommended,
    [EnumMember(Value = "migration")]
    Migration,
    [EnumMember(Value = "deprecated")]
    Deprecated,
}

public sealed class DomainData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("domain")]
    public string? Domain { get; set; }

    [JsonPropertyName("dkim_mode")]
    public DkimMode? DkimMode { get; set; }

    [JsonPropertyName("rotation_ready")]
    public bool? RotationReady { get; set; }

    [JsonPropertyName("status_changed_at")]
    public string? StatusChangedAt { get; set; }

    [JsonPropertyName("dns_records")]
    public List<DomainDnsRecordData>? DnsRecords { get; set; }

    [JsonPropertyName("projects")]
    public List<DomainDataProjectsItem>? Projects { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

public sealed class DomainDataProjectsItem : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

public sealed class DomainDestroyResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class DomainDnsRecordData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public RecordType? Type { get; set; }

    [JsonPropertyName("hostname")]
    public string? Hostname { get; set; }

    [JsonPropertyName("fqdn")]
    public string? Fqdn { get; set; }

    [JsonPropertyName("content")]
    public string? Content { get; set; }

    [JsonPropertyName("status")]
    public DnsRecordStatus? Status { get; set; }

    [JsonPropertyName("purpose")]
    public DnsRecordPurpose? Purpose { get; set; }

    [JsonPropertyName("verification_scope")]
    public DnsVerificationScope? VerificationScope { get; set; }

    [JsonPropertyName("required_for_verification")]
    public bool? RequiredForVerification { get; set; }

    [JsonPropertyName("verified_at")]
    public string? VerifiedAt { get; set; }

    [JsonPropertyName("last_checked_at")]
    public string? LastCheckedAt { get; set; }

}

public sealed class DomainIndexResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<DomainListData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class DomainListData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("domain")]
    public string? Domain { get; set; }

    [JsonPropertyName("status")]
    public DomainStatus? Status { get; set; }

    [JsonPropertyName("dkim_mode")]
    public DkimMode? DkimMode { get; set; }

    [JsonPropertyName("status_changed_at")]
    public string? StatusChangedAt { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<DomainStatus>))]
public enum DomainStatus
{
    [EnumMember(Value = "verified")]
    Verified,
    [EnumMember(Value = "partially_verified")]
    PartiallyVerified,
    [EnumMember(Value = "pending_verification")]
    PendingVerification,
    [EnumMember(Value = "failed_verification")]
    FailedVerification,
}

public sealed class DomainUpdateProjectsResponse : ApiModel
{
    [JsonPropertyName("data")]
    public DomainData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class DomainVerifyDnsRecordsResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("recommended_failed_records")]
    public List<DomainVerifyDnsRecordsResponseRecommendedFailedRecordsItem>? RecommendedFailedRecords { get; set; }

}

public sealed class DomainVerifyDnsRecordsResponseRecommendedFailedRecordsItem : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

public sealed class DomainVerifySpecificDnsRecordResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<InitialRoutes>))]
public enum InitialRoutes
{
    [EnumMember(Value = "both")]
    Both,
    [EnumMember(Value = "transactional")]
    Transactional,
    [EnumMember(Value = "broadcast")]
    Broadcast,
}

public sealed class MessageAttachmentData : ApiModel
{
    [JsonPropertyName("size")]
    public long? Size { get; set; }

    [JsonPropertyName("filename")]
    public string? Filename { get; set; }

    [JsonPropertyName("content_id")]
    public string? ContentId { get; set; }

    [JsonPropertyName("content_type")]
    public string? ContentType { get; set; }

}

public sealed class MessageData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public MessageType? Type { get; set; }

    [JsonPropertyName("status")]
    public MessageStatus? Status { get; set; }

    [JsonPropertyName("status_changed_at")]
    public string? StatusChangedAt { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

    [JsonPropertyName("tag")]
    public string? Tag { get; set; }

    [JsonPropertyName("tags")]
    public List<MessageDataTagsItem>? Tags { get; set; }

    [JsonPropertyName("from_email")]
    public string? FromEmail { get; set; }

    [JsonPropertyName("from_name")]
    public string? FromName { get; set; }

    [JsonPropertyName("reply_to")]
    public List<string>? ReplyTo { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("to")]
    public List<MessageRecipientData>? To { get; set; }

    [JsonPropertyName("cc")]
    public List<MessageRecipientData>? Cc { get; set; }

    [JsonPropertyName("bcc")]
    public List<MessageRecipientData>? Bcc { get; set; }

    [JsonPropertyName("attachments")]
    public List<MessageAttachmentData>? Attachments { get; set; }

    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; set; }

    [JsonPropertyName("spam_score")]
    public double? SpamScore { get; set; }

    [JsonPropertyName("spam_symbols")]
    public List<SpamSymbol>? SpamSymbols { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

public sealed class MessageDataTagsItem : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("value")]
    public string? Value { get; set; }

}

public sealed class MessageEventData : ApiModel
{
    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("event")]
    public MessageEventType? Event { get; set; }

    [JsonPropertyName("tag")]
    public string? Tag { get; set; }

    [JsonPropertyName("tags")]
    public List<MessageEventDataTagsItem>? Tags { get; set; }

    [JsonPropertyName("metadata")]
    public Dictionary<string, JsonElement>? Metadata { get; set; }

    [JsonPropertyName("timestamp")]
    public string? Timestamp { get; set; }

}

public sealed class MessageEventDataTagsItem : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("value")]
    public string? Value { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<MessageEventType>))]
public enum MessageEventType
{
    [EnumMember(Value = "scheduled")]
    Scheduled,
    [EnumMember(Value = "rescheduled")]
    Rescheduled,
    [EnumMember(Value = "canceled")]
    Canceled,
    [EnumMember(Value = "released")]
    Released,
    [EnumMember(Value = "queued")]
    Queued,
    [EnumMember(Value = "processed")]
    Processed,
    [EnumMember(Value = "suppressed")]
    Suppressed,
    [EnumMember(Value = "delivered")]
    Delivered,
    [EnumMember(Value = "auto_replied")]
    AutoReplied,
    [EnumMember(Value = "soft_bounced")]
    SoftBounced,
    [EnumMember(Value = "hard_bounced")]
    HardBounced,
    [EnumMember(Value = "spam_complaint")]
    SpamComplaint,
    [EnumMember(Value = "failed")]
    Failed,
    [EnumMember(Value = "blocked")]
    Blocked,
    [EnumMember(Value = "policy_rejected")]
    PolicyRejected,
    [EnumMember(Value = "unsubscribed")]
    Unsubscribed,
    [EnumMember(Value = "opened")]
    Opened,
    [EnumMember(Value = "clicked")]
    Clicked,
    [EnumMember(Value = "inbound_received")]
    InboundReceived,
    [EnumMember(Value = "inbound_queued")]
    InboundQueued,
    [EnumMember(Value = "inbound_spam_blocked")]
    InboundSpamBlocked,
    [EnumMember(Value = "inbound_released")]
    InboundReleased,
    [EnumMember(Value = "inbound_processed")]
    InboundProcessed,
    [EnumMember(Value = "inbound_retry")]
    InboundRetry,
}

public sealed class MessageEventsResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<MessageEventData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class MessageIndexResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<MessageListData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class MessageListData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public MessageType? Type { get; set; }

    [JsonPropertyName("status")]
    public MessageStatus? Status { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

    [JsonPropertyName("spam_score")]
    public double? SpamScore { get; set; }

    [JsonPropertyName("from_email")]
    public string? FromEmail { get; set; }

    [JsonPropertyName("from_name")]
    public string? FromName { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("to")]
    public List<MessageRecipientData>? To { get; set; }

    [JsonPropertyName("cc")]
    public List<MessageRecipientData>? Cc { get; set; }

    [JsonPropertyName("bcc")]
    public List<MessageRecipientData>? Bcc { get; set; }

    [JsonPropertyName("reply_to")]
    public List<string>? ReplyTo { get; set; }

    [JsonPropertyName("tag")]
    public string? Tag { get; set; }

    [JsonPropertyName("tags")]
    public List<MessageListDataTagsItem>? Tags { get; set; }

    [JsonPropertyName("status_changed_at")]
    public string? StatusChangedAt { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

public sealed class MessageListDataTagsItem : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("value")]
    public string? Value { get; set; }

}

public sealed class MessageRecipientData : ApiModel
{
    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

public sealed class MessageStatsData : ApiModel
{
    [JsonPropertyName("messages_transactional")]
    public long? MessagesTransactional { get; set; }

    [JsonPropertyName("messages_broadcast")]
    public long? MessagesBroadcast { get; set; }

    [JsonPropertyName("messages_inbound")]
    public long? MessagesInbound { get; set; }

    [JsonPropertyName("deliverability")]
    public double? Deliverability { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<MessageStatus>))]
public enum MessageStatus
{
    [EnumMember(Value = "scheduled")]
    Scheduled,
    [EnumMember(Value = "pending")]
    Pending,
    [EnumMember(Value = "queued")]
    Queued,
    [EnumMember(Value = "quarantined")]
    Quarantined,
    [EnumMember(Value = "suppressed")]
    Suppressed,
    [EnumMember(Value = "processed")]
    Processed,
    [EnumMember(Value = "delivered")]
    Delivered,
    [EnumMember(Value = "opened")]
    Opened,
    [EnumMember(Value = "clicked")]
    Clicked,
    [EnumMember(Value = "soft_bounced")]
    SoftBounced,
    [EnumMember(Value = "hard_bounced")]
    HardBounced,
    [EnumMember(Value = "spam_complaint")]
    SpamComplaint,
    [EnumMember(Value = "failed")]
    Failed,
    [EnumMember(Value = "blocked")]
    Blocked,
    [EnumMember(Value = "policy_rejected")]
    PolicyRejected,
    [EnumMember(Value = "unsubscribed")]
    Unsubscribed,
    [EnumMember(Value = "canceled")]
    Canceled,
}

[JsonConverter(typeof(WireEnumConverter<MessageType>))]
public enum MessageType
{
    [EnumMember(Value = "inbound")]
    Inbound,
    [EnumMember(Value = "outbound")]
    Outbound,
}

[JsonConverter(typeof(WireEnumConverter<Plan>))]
public enum Plan
{
    [EnumMember(Value = "free")]
    Free,
    [EnumMember(Value = "starter")]
    Starter,
    [EnumMember(Value = "growth")]
    Growth,
    [EnumMember(Value = "pro")]
    Pro,
}

public sealed class ProcessInboundMessageResponse : ApiModel
{
    [JsonPropertyName("data")]
    public ProcessInboundMessageResponseData? Data { get; set; }

}

public sealed class ProcessInboundMessageResponseData : ApiModel
{
    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    [JsonPropertyName("webhook_target_count")]
    public long? WebhookTargetCount { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<ProjectAccessScope>))]
public enum ProjectAccessScope
{
    [EnumMember(Value = "all")]
    All,
    [EnumMember(Value = "selected")]
    Selected,
}

public sealed class ProjectData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("smtp_enabled")]
    public bool? SmtpEnabled { get; set; }

    [JsonPropertyName("redact_email_content")]
    public bool? RedactEmailContent { get; set; }

    [JsonPropertyName("default_route_id")]
    public string? DefaultRouteId { get; set; }

    [JsonPropertyName("token_generated_at")]
    public string? TokenGeneratedAt { get; set; }

    [JsonPropertyName("token_last_used_at")]
    public string? TokenLastUsedAt { get; set; }

    [JsonPropertyName("token_last_used_ip")]
    public string? TokenLastUsedIp { get; set; }

    [JsonPropertyName("routes")]
    public List<RouteData>? Routes { get; set; }

    [JsonPropertyName("routes_count")]
    public long? RoutesCount { get; set; }

    [JsonPropertyName("domains")]
    public List<DomainData>? Domains { get; set; }

    [JsonPropertyName("domains_count")]
    public long? DomainsCount { get; set; }

    [JsonPropertyName("last_28_days")]
    public MessageStatsData? Last28Days { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class ProjectDestroyResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class ProjectIndexResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<ProjectListData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class ProjectListData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("smtp_enabled")]
    public bool? SmtpEnabled { get; set; }

    [JsonPropertyName("routes_count")]
    public long? RoutesCount { get; set; }

    [JsonPropertyName("domains_count")]
    public long? DomainsCount { get; set; }

    [JsonPropertyName("last_28_days")]
    public MessageStatsData? Last28Days { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class ProjectRotateTokenResponse : ApiModel
{
    [JsonPropertyName("data")]
    public ProjectData? Data { get; set; }

    [JsonPropertyName("new_token")]
    public string? NewToken { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class ProjectStoreResponse : ApiModel
{
    [JsonPropertyName("data")]
    public ProjectData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("api_token")]
    public string? ApiToken { get; set; }

}

public sealed class ProjectUpdateResponse : ApiModel
{
    [JsonPropertyName("data")]
    public ProjectData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<RbacConflictCode>))]
public enum RbacConflictCode
{
    [EnumMember(Value = "stale_resource")]
    StaleResource,
    [EnumMember(Value = "owner_protected")]
    OwnerProtected,
    [EnumMember(Value = "last_owner")]
    LastOwner,
    [EnumMember(Value = "built_in_role_immutable")]
    BuiltInRoleImmutable,
    [EnumMember(Value = "custom_role_requires_pro")]
    CustomRoleRequiresPro,
}

[JsonConverter(typeof(WireEnumConverter<RbacPermission>))]
public enum RbacPermission
{
    [EnumMember(Value = "team:manage")]
    TeamManage,
    [EnumMember(Value = "billing:manage")]
    BillingManage,
    [EnumMember(Value = "security:manage")]
    SecurityManage,
    [EnumMember(Value = "audit:read")]
    AuditRead,
    [EnumMember(Value = "support:manage")]
    SupportManage,
    [EnumMember(Value = "members:read")]
    MembersRead,
    [EnumMember(Value = "members:manage")]
    MembersManage,
    [EnumMember(Value = "roles:manage")]
    RolesManage,
    [EnumMember(Value = "team_tokens:read")]
    TeamTokensRead,
    [EnumMember(Value = "team_tokens:manage")]
    TeamTokensManage,
    [EnumMember(Value = "team_tokens:rotate")]
    TeamTokensRotate,
    [EnumMember(Value = "team_tokens:revoke")]
    TeamTokensRevoke,
    [EnumMember(Value = "projects:create")]
    ProjectsCreate,
    [EnumMember(Value = "team_suppressions:read")]
    TeamSuppressionsRead,
    [EnumMember(Value = "team_suppressions:add")]
    TeamSuppressionsAdd,
    [EnumMember(Value = "team_suppressions:remove")]
    TeamSuppressionsRemove,
    [EnumMember(Value = "projects:read")]
    ProjectsRead,
    [EnumMember(Value = "projects:manage")]
    ProjectsManage,
    [EnumMember(Value = "projects:delete")]
    ProjectsDelete,
    [EnumMember(Value = "routes:read")]
    RoutesRead,
    [EnumMember(Value = "routes:manage")]
    RoutesManage,
    [EnumMember(Value = "routes:delete")]
    RoutesDelete,
    [EnumMember(Value = "domains:read")]
    DomainsRead,
    [EnumMember(Value = "domains:manage")]
    DomainsManage,
    [EnumMember(Value = "domains:delete")]
    DomainsDelete,
    [EnumMember(Value = "project_tokens:read")]
    ProjectTokensRead,
    [EnumMember(Value = "project_tokens:manage")]
    ProjectTokensManage,
    [EnumMember(Value = "project_tokens:rotate")]
    ProjectTokensRotate,
    [EnumMember(Value = "project_tokens:revoke")]
    ProjectTokensRevoke,
    [EnumMember(Value = "webhooks:read")]
    WebhooksRead,
    [EnumMember(Value = "webhooks:manage")]
    WebhooksManage,
    [EnumMember(Value = "webhooks:delete")]
    WebhooksDelete,
    [EnumMember(Value = "webhooks:rotate_secret")]
    WebhooksRotateSecret,
    [EnumMember(Value = "stats:read")]
    StatsRead,
    [EnumMember(Value = "messages:read")]
    MessagesRead,
    [EnumMember(Value = "messages:read_content")]
    MessagesReadContent,
    [EnumMember(Value = "messages:send")]
    MessagesSend,
    [EnumMember(Value = "suppressions:read")]
    SuppressionsRead,
    [EnumMember(Value = "suppressions:add")]
    SuppressionsAdd,
    [EnumMember(Value = "suppressions:remove")]
    SuppressionsRemove,
}

[JsonConverter(typeof(WireEnumConverter<RecordType>))]
public enum RecordType
{
    [EnumMember(Value = "TXT")]
    TXT,
    [EnumMember(Value = "CNAME")]
    CNAME,
    [EnumMember(Value = "MX")]
    MX,
}

public sealed class RescheduleMessageRequest : ApiModel
{
    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

}

public sealed class RescheduleMessageResponse : ApiModel
{
    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("status")]
    public MessageStatus? Status { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

}

public sealed class RouteData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("project_id")]
    public string? ProjectId { get; set; }

    [JsonPropertyName("slug")]
    public string? Slug { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("route_type")]
    public RouteType? RouteType { get; set; }

    [JsonPropertyName("is_default")]
    public bool? IsDefault { get; set; }

    [JsonPropertyName("inbound_address")]
    public string? InboundAddress { get; set; }

    [JsonPropertyName("inbound_domain")]
    public string? InboundDomain { get; set; }

    [JsonPropertyName("inbound_domain_verified_at")]
    public string? InboundDomainVerifiedAt { get; set; }

    [JsonPropertyName("inbound_spam_threshold")]
    public double? InboundSpamThreshold { get; set; }

    [JsonPropertyName("attachment_delivery")]
    public AttachmentDelivery? AttachmentDelivery { get; set; }

    [JsonPropertyName("settings")]
    public RouteDataSettings? Settings { get; set; }

    [JsonPropertyName("project")]
    public ProjectData? Project { get; set; }

    [JsonPropertyName("webhooks_count")]
    public long? WebhooksCount { get; set; }

    [JsonPropertyName("suppressed_recipients_count")]
    public long? SuppressedRecipientsCount { get; set; }

    [JsonPropertyName("statistics")]
    public List<RouteStatisticData>? Statistics { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class RouteDataSettings : ApiModel
{
    [JsonPropertyName("disable_hosted_unsubscribe")]
    public bool? DisableHostedUnsubscribe { get; set; }

    [JsonPropertyName("track_opens")]
    public bool? TrackOpens { get; set; }

    [JsonPropertyName("track_clicks")]
    public bool? TrackClicks { get; set; }

    [JsonPropertyName("generate_plaintext_fallback")]
    public bool? GeneratePlaintextFallback { get; set; }

    [JsonPropertyName("suppress_auto_responders")]
    public bool? SuppressAutoResponders { get; set; }

    [JsonPropertyName("suppress_disposable_recipients")]
    public bool? SuppressDisposableRecipients { get; set; }

    [JsonPropertyName("tls")]
    public TlsPolicy? Tls { get; set; }

    [JsonPropertyName("redact_email_content")]
    public bool? RedactEmailContent { get; set; }

    [JsonPropertyName("attachment_delivery")]
    public AttachmentDelivery? AttachmentDelivery { get; set; }

}

public sealed class RouteDestroyResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class RouteIndexResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<RouteListData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class RouteListData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("slug")]
    public string? Slug { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("route_type")]
    public RouteType? RouteType { get; set; }

    [JsonPropertyName("is_default")]
    public bool? IsDefault { get; set; }

    [JsonPropertyName("webhooks_count")]
    public long? WebhooksCount { get; set; }

    [JsonPropertyName("suppressed_recipients_count")]
    public long? SuppressedRecipientsCount { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class RouteStatisticData : ApiModel
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("sent_count")]
    public long? SentCount { get; set; }

    [JsonPropertyName("delivered_count")]
    public long? DeliveredCount { get; set; }

    [JsonPropertyName("opened_count")]
    public long? OpenedCount { get; set; }

    [JsonPropertyName("clicked_count")]
    public long? ClickedCount { get; set; }

    [JsonPropertyName("hard_bounce_count")]
    public long? HardBounceCount { get; set; }

    [JsonPropertyName("spam_complaint_count")]
    public long? SpamComplaintCount { get; set; }

    [JsonPropertyName("inbound_received_count")]
    public long? InboundReceivedCount { get; set; }

    [JsonPropertyName("observed_opened_count")]
    public long? ObservedOpenedCount { get; set; }

    [JsonPropertyName("human_opened_count")]
    public long? HumanOpenedCount { get; set; }

    [JsonPropertyName("privacy_opened_count")]
    public long? PrivacyOpenedCount { get; set; }

    [JsonPropertyName("effective_opened_count")]
    public long? EffectiveOpenedCount { get; set; }

    [JsonPropertyName("machine_opened_count")]
    public long? MachineOpenedCount { get; set; }

    [JsonPropertyName("machine_clicked_count")]
    public long? MachineClickedCount { get; set; }

}

public sealed class RouteStoreResponse : ApiModel
{
    [JsonPropertyName("data")]
    public RouteData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<RouteType>))]
public enum RouteType
{
    [EnumMember(Value = "transactional")]
    Transactional,
    [EnumMember(Value = "broadcast")]
    Broadcast,
    [EnumMember(Value = "inbound")]
    Inbound,
}

public sealed class RouteUpdateResponse : ApiModel
{
    [JsonPropertyName("data")]
    public RouteData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class RouteVerifyInboundDomainResponse : ApiModel
{
    [JsonPropertyName("data")]
    public RouteVerifyInboundDomainResponseData? Data { get; set; }

}

public sealed class RouteVerifyInboundDomainResponseData : ApiModel
{
    [JsonPropertyName("verified")]
    public bool? Verified { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class SendBatchEmailResponseItem : ApiModel
{
    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("status")]
    public MessageStatus? Status { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

}

public sealed class SendBatchMailRequestItem : ApiModel
{
    [JsonPropertyName("route")]
    public string? Route { get; set; }

    [JsonPropertyName("from")]
    public string? From { get; set; }

    [JsonPropertyName("to")]
    public List<string>? To { get; set; }

    [JsonPropertyName("cc")]
    public List<string>? Cc { get; set; }

    [JsonPropertyName("bcc")]
    public List<string>? Bcc { get; set; }

    [JsonPropertyName("reply_to")]
    public List<string>? ReplyTo { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

    [JsonPropertyName("headers")]
    public Dictionary<string, string>? Headers { get; set; }

    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; set; }

    [JsonPropertyName("tag")]
    public string? Tag { get; set; }

    [JsonPropertyName("tags")]
    public List<SendBatchMailRequestItemTagsItem>? Tags { get; set; }

    [JsonPropertyName("settings")]
    public SendBatchMailRequestItemSettings? Settings { get; set; }

    [JsonPropertyName("html")]
    public string? Html { get; set; }

    [JsonPropertyName("text")]
    public string? Text { get; set; }

    [JsonPropertyName("attachments")]
    public List<SendBatchMailRequestItemAttachmentsItem>? Attachments { get; set; }

}

public sealed class SendBatchMailRequestItemAttachmentsItem : ApiModel
{
    [JsonPropertyName("filename")]
    public string? Filename { get; set; }

    [JsonPropertyName("content")]
    public string? Content { get; set; }

    [JsonPropertyName("content_type")]
    public string? ContentType { get; set; }

    [JsonPropertyName("content_id")]
    public string? ContentId { get; set; }

}

public sealed class SendBatchMailRequestItemSettings : ApiModel
{
    [JsonPropertyName("track_opens")]
    public bool? TrackOpens { get; set; }

    [JsonPropertyName("track_clicks")]
    public bool? TrackClicks { get; set; }

    [JsonPropertyName("tls")]
    public TlsPolicy? Tls { get; set; }

}

public sealed class SendBatchMailRequestItemTagsItem : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("value")]
    public string? Value { get; set; }

}

public sealed class SendEmailResponse : ApiModel
{
    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("status")]
    public MessageStatus? Status { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

}

public sealed class SendMailRequest : ApiModel
{
    [JsonPropertyName("route")]
    public string? Route { get; set; }

    [JsonPropertyName("from")]
    public string? From { get; set; }

    [JsonPropertyName("to")]
    public List<string>? To { get; set; }

    [JsonPropertyName("cc")]
    public List<string>? Cc { get; set; }

    [JsonPropertyName("bcc")]
    public List<string>? Bcc { get; set; }

    [JsonPropertyName("reply_to")]
    public List<string>? ReplyTo { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("scheduled_at")]
    public string? ScheduledAt { get; set; }

    [JsonPropertyName("headers")]
    public Dictionary<string, string>? Headers { get; set; }

    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; set; }

    [JsonPropertyName("tag")]
    public string? Tag { get; set; }

    [JsonPropertyName("tags")]
    public List<SendMailRequestTagsItem>? Tags { get; set; }

    [JsonPropertyName("settings")]
    public SendMailRequestSettings? Settings { get; set; }

    [JsonPropertyName("html")]
    public string? Html { get; set; }

    [JsonPropertyName("text")]
    public string? Text { get; set; }

    [JsonPropertyName("attachments")]
    public List<SendMailRequestAttachmentsItem>? Attachments { get; set; }

}

public sealed class SendMailRequestAttachmentsItem : ApiModel
{
    [JsonPropertyName("filename")]
    public string? Filename { get; set; }

    [JsonPropertyName("content")]
    public string? Content { get; set; }

    [JsonPropertyName("content_type")]
    public string? ContentType { get; set; }

    [JsonPropertyName("content_id")]
    public string? ContentId { get; set; }

}

public sealed class SendMailRequestSettings : ApiModel
{
    [JsonPropertyName("track_opens")]
    public bool? TrackOpens { get; set; }

    [JsonPropertyName("track_clicks")]
    public bool? TrackClicks { get; set; }

    [JsonPropertyName("tls")]
    public TlsPolicy? Tls { get; set; }

}

public sealed class SendMailRequestTagsItem : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("value")]
    public string? Value { get; set; }

}

public sealed class SpamSymbol : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("score")]
    public double? Score { get; set; }

    [JsonPropertyName("options")]
    public List<string>? Options { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

}

public sealed class StatsDailyData : ApiModel
{
    [JsonPropertyName("date")]
    public string? Date { get; set; }

    [JsonPropertyName("sent")]
    public long? Sent { get; set; }

    [JsonPropertyName("delivered")]
    public long? Delivered { get; set; }

    [JsonPropertyName("hard_bounced")]
    public long? HardBounced { get; set; }

    [JsonPropertyName("spam_complaints")]
    public long? SpamComplaints { get; set; }

    [JsonPropertyName("opened")]
    public long? Opened { get; set; }

    [JsonPropertyName("clicked")]
    public long? Clicked { get; set; }

    [JsonPropertyName("inbound")]
    public StatsInboundData? Inbound { get; set; }

    [JsonPropertyName("transactional")]
    public StatsTypeData? Transactional { get; set; }

    [JsonPropertyName("broadcast")]
    public StatsTypeData? Broadcast { get; set; }

    [JsonPropertyName("observed_opened")]
    public long? ObservedOpened { get; set; }

    [JsonPropertyName("human_opened")]
    public long? HumanOpened { get; set; }

    [JsonPropertyName("privacy_opened")]
    public long? PrivacyOpened { get; set; }

    [JsonPropertyName("effective_opened")]
    public long? EffectiveOpened { get; set; }

    [JsonPropertyName("machine_opened")]
    public long? MachineOpened { get; set; }

    [JsonPropertyName("machine_clicked")]
    public long? MachineClicked { get; set; }

}

public sealed class StatsData : ApiModel
{
    [JsonPropertyName("from")]
    public string? From { get; set; }

    [JsonPropertyName("to")]
    public string? To { get; set; }

    [JsonPropertyName("totals")]
    public StatsTotalsData? Totals { get; set; }

    [JsonPropertyName("daily")]
    public List<StatsDailyData>? Daily { get; set; }

}

public sealed class StatsInboundData : ApiModel
{
    [JsonPropertyName("received")]
    public long? Received { get; set; }

}

public sealed class StatsRequestData : ApiModel
{
    [JsonPropertyName("from")]
    public string? From { get; set; }

    [JsonPropertyName("to")]
    public string? To { get; set; }

    [JsonPropertyName("project_id")]
    public string? ProjectId { get; set; }

    [JsonPropertyName("include_machine")]
    public bool? IncludeMachine { get; set; }

}

public sealed class StatsTotalsData : ApiModel
{
    [JsonPropertyName("sent")]
    public long? Sent { get; set; }

    [JsonPropertyName("delivered")]
    public long? Delivered { get; set; }

    [JsonPropertyName("hard_bounced")]
    public long? HardBounced { get; set; }

    [JsonPropertyName("spam_complaints")]
    public long? SpamComplaints { get; set; }

    [JsonPropertyName("opened")]
    public long? Opened { get; set; }

    [JsonPropertyName("clicked")]
    public long? Clicked { get; set; }

    [JsonPropertyName("inbound")]
    public StatsInboundData? Inbound { get; set; }

    [JsonPropertyName("transactional")]
    public StatsTypeData? Transactional { get; set; }

    [JsonPropertyName("broadcast")]
    public StatsTypeData? Broadcast { get; set; }

    [JsonPropertyName("observed_opened")]
    public long? ObservedOpened { get; set; }

    [JsonPropertyName("human_opened")]
    public long? HumanOpened { get; set; }

    [JsonPropertyName("privacy_opened")]
    public long? PrivacyOpened { get; set; }

    [JsonPropertyName("effective_opened")]
    public long? EffectiveOpened { get; set; }

    [JsonPropertyName("machine_opened")]
    public long? MachineOpened { get; set; }

    [JsonPropertyName("machine_clicked")]
    public long? MachineClicked { get; set; }

}

public sealed class StatsTypeData : ApiModel
{
    [JsonPropertyName("sent")]
    public long? Sent { get; set; }

    [JsonPropertyName("hard_bounced")]
    public long? HardBounced { get; set; }

    [JsonPropertyName("spam_complaints")]
    public long? SpamComplaints { get; set; }

}

public sealed class StoreDomainData : ApiModel
{
    [JsonPropertyName("domain")]
    public string? Domain { get; set; }

}

public sealed class StoreProjectData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("smtp_enabled")]
    public bool? SmtpEnabled { get; set; }

    [JsonPropertyName("initial_routes")]
    public InitialRoutes? InitialRoutes { get; set; }

    [JsonPropertyName("short_token")]
    public bool? ShortToken { get; set; }

}

public sealed class StoreRouteData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("route_type")]
    public RouteType? RouteType { get; set; }

    [JsonPropertyName("slug")]
    public string? Slug { get; set; }

}

public sealed class StoreSuppressionData : ApiModel
{
    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("emails")]
    public List<string>? Emails { get; set; }

    [JsonPropertyName("reason")]
    public SuppressionReason? Reason { get; set; }

    [JsonPropertyName("scope")]
    public SuppressionScope? Scope { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

    [JsonPropertyName("project_id")]
    public string? ProjectId { get; set; }

    [JsonPropertyName("applies_to")]
    public SuppressionAppliesTo? AppliesTo { get; set; }

}

public sealed class StoreWebhookData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("events")]
    public List<WebhookEvent>? Events { get; set; }

    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }

    [JsonPropertyName("include_machine_events")]
    public bool? IncludeMachineEvents { get; set; }

    [JsonPropertyName("scope")]
    public WebhookScope? Scope { get; set; }

    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

    [JsonPropertyName("route_ids")]
    public List<string>? RouteIds { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

}

public sealed class SuppressedRecipientData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public SuppressionType? Type { get; set; }

    [JsonPropertyName("value")]
    public string? Value { get; set; }

    [JsonPropertyName("reason")]
    public SuppressionReason? Reason { get; set; }

    [JsonPropertyName("scope")]
    public SuppressionScope? Scope { get; set; }

    [JsonPropertyName("applies_to")]
    public SuppressionAppliesTo? AppliesTo { get; set; }

    [JsonPropertyName("project_id")]
    public string? ProjectId { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

    [JsonPropertyName("source_message")]
    public SuppressionSourceMessageData? SourceMessage { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<SuppressionAppliesTo>))]
public enum SuppressionAppliesTo
{
    [EnumMember(Value = "all")]
    All,
    [EnumMember(Value = "broadcast")]
    Broadcast,
}

public sealed class SuppressionDestroyResponse : ApiModel
{
    [JsonPropertyName("success")]
    public bool? Success { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("confidence")]
    public double? Confidence { get; set; }

    [JsonPropertyName("ticket_identifier")]
    public string? TicketIdentifier { get; set; }

}

public sealed class SuppressionIndexResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<SuppressedRecipientData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<SuppressionReason>))]
public enum SuppressionReason
{
    [EnumMember(Value = "spam_complaint")]
    SpamComplaint,
    [EnumMember(Value = "hard_bounce")]
    HardBounce,
    [EnumMember(Value = "unsubscribe")]
    Unsubscribe,
    [EnumMember(Value = "manual")]
    Manual,
}

[JsonConverter(typeof(WireEnumConverter<SuppressionScope>))]
public enum SuppressionScope
{
    [EnumMember(Value = "team")]
    Team,
    [EnumMember(Value = "project")]
    Project,
    [EnumMember(Value = "route")]
    Route,
}

public sealed class SuppressionSourceMessageData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("available")]
    public bool? Available { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

public sealed class SuppressionStoreResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("data")]
    public SuppressionStoreResponseData? Data { get; set; }

}

public sealed class SuppressionStoreResponseData : ApiModel
{
    [JsonPropertyName("created")]
    public List<string>? Created { get; set; }

    [JsonPropertyName("skipped")]
    public List<string>? Skipped { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<SuppressionType>))]
public enum SuppressionType
{
    [EnumMember(Value = "email")]
    Email,
    [EnumMember(Value = "domain")]
    Domain,
    [EnumMember(Value = "extension")]
    Extension,
}

public sealed class TeamAddonData : ApiModel
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("expires_at")]
    public string? ExpiresAt { get; set; }

}

public sealed class TeamData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("type")]
    public TeamType? Type { get; set; }

    [JsonPropertyName("plan")]
    public Plan? Plan { get; set; }

    [JsonPropertyName("included_volume")]
    public long? IncludedVolume { get; set; }

    [JsonPropertyName("tier")]
    public long? Tier { get; set; }

    [JsonPropertyName("verified_at")]
    public string? VerifiedAt { get; set; }

    [JsonPropertyName("features")]
    public List<string>? Features { get; set; }

    [JsonPropertyName("addons")]
    public List<TeamAddonData>? Addons { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("domains_count")]
    public long? DomainsCount { get; set; }

    [JsonPropertyName("projects_count")]
    public long? ProjectsCount { get; set; }

    [JsonPropertyName("members_count")]
    public long? MembersCount { get; set; }

}

public sealed class TeamMemberData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("email")]
    public string? Email { get; set; }

    [JsonPropertyName("role")]
    public TeamMemberDataRole? Role { get; set; }

    [JsonPropertyName("project_access")]
    public TeamMemberProjectAccessData? ProjectAccess { get; set; }

    [JsonPropertyName("joined_at")]
    public string? JoinedAt { get; set; }

}

public sealed class TeamMemberDataRole : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

public sealed class TeamMemberProjectAccessData : ApiModel
{
    [JsonPropertyName("scope")]
    public ProjectAccessScope? Scope { get; set; }

    [JsonPropertyName("projects")]
    public List<TeamMemberProjectAccessDataProjectsItem>? Projects { get; set; }

}

public sealed class TeamMemberProjectAccessDataProjectsItem : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

public sealed class TeamMembersResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<TeamMemberData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class TeamRoleData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("system_key")]
    public BuiltInTeamRole? SystemKey { get; set; }

    [JsonPropertyName("permissions")]
    public List<RbacPermission>? Permissions { get; set; }

    [JsonPropertyName("assignable")]
    public bool? Assignable { get; set; }

}

public sealed class TeamRolesResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<TeamRoleData>? Data { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<TeamType>))]
public enum TeamType
{
    [EnumMember(Value = "personal")]
    Personal,
    [EnumMember(Value = "business")]
    Business,
}

public sealed class TeamUpdateResponse : ApiModel
{
    [JsonPropertyName("data")]
    public TeamData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class TeamUsageDetailData : ApiModel
{
    [JsonPropertyName("current_period")]
    public TeamUsagePeriodData? CurrentPeriod { get; set; }

    [JsonPropertyName("historical_usage")]
    public List<TeamUsagePeriodData>? HistoricalUsage { get; set; }

}

public sealed class TeamUsagePeriodData : ApiModel
{
    [JsonPropertyName("usage")]
    public long? Usage { get; set; }

    [JsonPropertyName("last_incremented_at")]
    public string? LastIncrementedAt { get; set; }

    [JsonPropertyName("period_start")]
    public string? PeriodStart { get; set; }

    [JsonPropertyName("period_end")]
    public string? PeriodEnd { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<TlsPolicy>))]
public enum TlsPolicy
{
    [EnumMember(Value = "opportunistic")]
    Opportunistic,
    [EnumMember(Value = "enforced")]
    Enforced,
}

public sealed class UpdateDomainProjectsData : ApiModel
{
    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

}

public sealed class UpdateProjectData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("smtp_enabled")]
    public bool? SmtpEnabled { get; set; }

    [JsonPropertyName("redact_email_content")]
    public bool? RedactEmailContent { get; set; }

    [JsonPropertyName("default_route_id")]
    public string? DefaultRouteId { get; set; }

}

public sealed class UpdateRouteData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("settings")]
    public UpdateRouteSettingsData? Settings { get; set; }

    [JsonPropertyName("inbound_settings")]
    public UpdateRouteInboundSettingsData? InboundSettings { get; set; }

}

public sealed class UpdateRouteInboundSettingsData : ApiModel
{
    [JsonPropertyName("inbound_domain")]
    public string? InboundDomain { get; set; }

    [JsonPropertyName("inbound_spam_threshold")]
    public double? InboundSpamThreshold { get; set; }

    [JsonPropertyName("attachment_delivery")]
    public AttachmentDelivery? AttachmentDelivery { get; set; }

}

public sealed class UpdateRouteSettingsData : ApiModel
{
    [JsonPropertyName("track_opens")]
    public bool? TrackOpens { get; set; }

    [JsonPropertyName("track_clicks")]
    public bool? TrackClicks { get; set; }

    [JsonPropertyName("generate_plaintext_fallback")]
    public bool? GeneratePlaintextFallback { get; set; }

    [JsonPropertyName("suppress_auto_responders")]
    public bool? SuppressAutoResponders { get; set; }

    [JsonPropertyName("suppress_disposable_recipients")]
    public bool? SuppressDisposableRecipients { get; set; }

    [JsonPropertyName("tls")]
    public TlsPolicy? Tls { get; set; }

    [JsonPropertyName("disable_hosted_unsubscribe")]
    public bool? DisableHostedUnsubscribe { get; set; }

    [JsonPropertyName("redact_email_content")]
    public bool? RedactEmailContent { get; set; }

}

public sealed class UpdateTeamData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

public sealed class UpdateTeamMemberAssignmentData : ApiModel
{
    [JsonPropertyName("role_id")]
    public string? RoleId { get; set; }

    [JsonPropertyName("project_access")]
    public UpdateTeamMemberAssignmentDataProjectAccess? ProjectAccess { get; set; }

}

public sealed class UpdateTeamMemberAssignmentDataProjectAccess : ApiModel
{
    [JsonPropertyName("scope")]
    public ProjectAccessScope? Scope { get; set; }

    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

}

public sealed class UpdateWebhookData : ApiModel
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("events")]
    public List<WebhookEvent>? Events { get; set; }

    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }

    [JsonPropertyName("include_machine_events")]
    public bool? IncludeMachineEvents { get; set; }

    [JsonPropertyName("scope")]
    public WebhookScope? Scope { get; set; }

    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

    [JsonPropertyName("route_ids")]
    public List<string>? RouteIds { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

}

public sealed class V1BlockedFileTypesResponse : ApiModel
{
    [JsonPropertyName("extensions")]
    public List<string>? Extensions { get; set; }

    [JsonPropertyName("mime_types")]
    public List<string>? MimeTypes { get; set; }

}

public sealed class WebhookData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("scope")]
    public WebhookScope? Scope { get; set; }

    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

    [JsonPropertyName("route_ids")]
    public List<string>? RouteIds { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("events")]
    public List<string>? Events { get; set; }

    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }

    [JsonPropertyName("include_machine_events")]
    public bool? IncludeMachineEvents { get; set; }

    [JsonPropertyName("last_called_at")]
    public string? LastCalledAt { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class WebhookDeliveriesResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<WebhookDeliveryListData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class WebhookDeliveryData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("webhook_id")]
    public string? WebhookId { get; set; }

    [JsonPropertyName("event_type")]
    public WebhookEvent? EventType { get; set; }

    [JsonPropertyName("source_scope")]
    public string? SourceScope { get; set; }

    [JsonPropertyName("source_project_id")]
    public string? SourceProjectId { get; set; }

    [JsonPropertyName("source_route_id")]
    public string? SourceRouteId { get; set; }

    [JsonPropertyName("status")]
    public WebhookDeliveryStatus? Status { get; set; }

    [JsonPropertyName("attempt_number")]
    public long? AttemptNumber { get; set; }

    [JsonPropertyName("http_status_code")]
    public long? HttpStatusCode { get; set; }

    [JsonPropertyName("duration_ms")]
    public long? DurationMs { get; set; }

    [JsonPropertyName("payload")]
    public List<string>? Payload { get; set; }

    [JsonPropertyName("response_body")]
    public string? ResponseBody { get; set; }

    [JsonPropertyName("response_headers")]
    public List<string>? ResponseHeaders { get; set; }

    [JsonPropertyName("error_message")]
    public string? ErrorMessage { get; set; }

    [JsonPropertyName("delivered_at")]
    public string? DeliveredAt { get; set; }

    [JsonPropertyName("timestamp")]
    public string? Timestamp { get; set; }

}

public sealed class WebhookDeliveryListData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("webhook_id")]
    public string? WebhookId { get; set; }

    [JsonPropertyName("event_type")]
    public WebhookEvent? EventType { get; set; }

    [JsonPropertyName("source_scope")]
    public string? SourceScope { get; set; }

    [JsonPropertyName("source_project_id")]
    public string? SourceProjectId { get; set; }

    [JsonPropertyName("source_route_id")]
    public string? SourceRouteId { get; set; }

    [JsonPropertyName("status")]
    public WebhookDeliveryStatus? Status { get; set; }

    [JsonPropertyName("attempt_number")]
    public long? AttemptNumber { get; set; }

    [JsonPropertyName("http_status_code")]
    public long? HttpStatusCode { get; set; }

    [JsonPropertyName("duration_ms")]
    public long? DurationMs { get; set; }

    [JsonPropertyName("delivered_at")]
    public string? DeliveredAt { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<WebhookDeliveryStatus>))]
public enum WebhookDeliveryStatus
{
    [EnumMember(Value = "pending")]
    Pending,
    [EnumMember(Value = "success")]
    Success,
    [EnumMember(Value = "failed")]
    Failed,
    [EnumMember(Value = "client_error")]
    ClientError,
    [EnumMember(Value = "server_error")]
    ServerError,
    [EnumMember(Value = "timeout")]
    Timeout,
}

public sealed class WebhookDestroyResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<WebhookEvent>))]
public enum WebhookEvent
{
    [EnumMember(Value = "message.created")]
    MessageCreated,
    [EnumMember(Value = "message.sent")]
    MessageSent,
    [EnumMember(Value = "message.delivered")]
    MessageDelivered,
    [EnumMember(Value = "message.auto_replied")]
    MessageAutoReplied,
    [EnumMember(Value = "message.hard_bounced")]
    MessageHardBounced,
    [EnumMember(Value = "message.soft_bounced")]
    MessageSoftBounced,
    [EnumMember(Value = "message.spam_complaint")]
    MessageSpamComplaint,
    [EnumMember(Value = "message.failed")]
    MessageFailed,
    [EnumMember(Value = "message.suppressed")]
    MessageSuppressed,
    [EnumMember(Value = "message.unsubscribed")]
    MessageUnsubscribed,
    [EnumMember(Value = "message.opened")]
    MessageOpened,
    [EnumMember(Value = "message.clicked")]
    MessageClicked,
    [EnumMember(Value = "message.inbound")]
    MessageInbound,
    [EnumMember(Value = "message.policy_rejected")]
    MessagePolicyRejected,
    [EnumMember(Value = "message.scheduled")]
    MessageScheduled,
    [EnumMember(Value = "message.rescheduled")]
    MessageRescheduled,
    [EnumMember(Value = "message.canceled")]
    MessageCanceled,
    [EnumMember(Value = "message.released")]
    MessageReleased,
    [EnumMember(Value = "suppression.added")]
    SuppressionAdded,
    [EnumMember(Value = "suppression.removed")]
    SuppressionRemoved,
    [EnumMember(Value = "webhook.test")]
    WebhookTest,
}

public sealed class WebhookIndexResponse : ApiModel
{
    [JsonPropertyName("data")]
    public List<WebhookListData>? Data { get; set; }

    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("per_page")]
    public long? PerPage { get; set; }

    [JsonPropertyName("next_cursor")]
    public string? NextCursor { get; set; }

    [JsonPropertyName("next_page_url")]
    public string? NextPageUrl { get; set; }

    [JsonPropertyName("prev_cursor")]
    public string? PrevCursor { get; set; }

    [JsonPropertyName("prev_page_url")]
    public string? PrevPageUrl { get; set; }

}

public sealed class WebhookListData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("scope")]
    public WebhookScope? Scope { get; set; }

    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

    [JsonPropertyName("route_ids")]
    public List<string>? RouteIds { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("events")]
    public List<string>? Events { get; set; }

    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }

    [JsonPropertyName("last_called_at")]
    public string? LastCalledAt { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class WebhookRegenerateSecretResponse : ApiModel
{
    [JsonPropertyName("data")]
    public WebhookSecretData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

[JsonConverter(typeof(WireEnumConverter<WebhookScope>))]
public enum WebhookScope
{
    [EnumMember(Value = "team")]
    Team,
    [EnumMember(Value = "project")]
    Project,
    [EnumMember(Value = "route")]
    Route,
}

public sealed class WebhookSecretData : ApiModel
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("scope")]
    public WebhookScope? Scope { get; set; }

    [JsonPropertyName("project_ids")]
    public List<string>? ProjectIds { get; set; }

    [JsonPropertyName("route_ids")]
    public List<string>? RouteIds { get; set; }

    [JsonPropertyName("route_id")]
    public string? RouteId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("events")]
    public List<string>? Events { get; set; }

    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }

    [JsonPropertyName("include_machine_events")]
    public bool? IncludeMachineEvents { get; set; }

    [JsonPropertyName("secret")]
    public string? Secret { get; set; }

    [JsonPropertyName("last_called_at")]
    public string? LastCalledAt { get; set; }

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }

}

public sealed class WebhookStoreResponse : ApiModel
{
    [JsonPropertyName("data")]
    public WebhookSecretData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}

public sealed class WebhookTestResponse : ApiModel
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("delivery_id")]
    public string? DeliveryId { get; set; }

}

public sealed class WebhookUpdateResponse : ApiModel
{
    [JsonPropertyName("data")]
    public WebhookData? Data { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}
