#!/usr/bin/env python3
"""Regenerate (or, with --check, verify) src/Lettermint/Generated/ with the private
lettermint/sdk-generator.

Set LETTERMINT_SDK_GENERATOR to its checkout (default: ../sdk-generator next to
this repository). Without the generator (CI, contributors without access),
--check only verifies that every generated file carries the generator header
with the spec commit and hashes, so that hand edits that drop the header are
caught.
"""
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "Lettermint" / "Generated"
FILES = ("Types.g.cs", "Operations.g.cs", "Runtime.g.cs")
HEADER = [
    re.compile(r"^// <auto-generated />$"),
    re.compile(r"^// Generated by lettermint/sdk-generator — do not edit\.$"),
    re.compile(r"^// Spec: lettermint/lettermint@[0-9a-f]{40}( \(.+\))?$"),
    re.compile(r"^// sending-openapi\.json SHA-256: [0-9a-f]{64}$"),
    re.compile(r"^// team-openapi\.json SHA-256: [0-9a-f]{64}$"),
    re.compile(r"^// Naming profile: next$"),
]


def main() -> int:
    check = "--check" in sys.argv[1:]
    generator = (ROOT / os.environ.get("LETTERMINT_SDK_GENERATOR", "../sdk-generator")).resolve()
    if (generator / "lettermint_sdkgen").is_dir() and (generator / "spec.next.lock.json").is_file():
        command = [sys.executable, "-m", "lettermint_sdkgen", "emit", "csharp", "--profile", "next", "--lock", "spec.next.lock.json", "--out", str(OUT)]
        if check:
            command.append("--check")
        return subprocess.run(command, cwd=generator).returncode

    if not check:
        print(f"The SDK generator was not found at {generator}. Set LETTERMINT_SDK_GENERATOR to its checkout.", file=sys.stderr)
        return 1

    headers = []
    for name in FILES:
        path = OUT / name
        lines = path.read_text(encoding="utf-8").splitlines()[: len(HEADER)] if path.exists() else []
        if len(lines) != len(HEADER) or not all(pattern.match(line) for pattern, line in zip(HEADER, lines)):
            print(f"src/Lettermint/Generated/{name} is missing the generator header. Regenerate it; do not edit it by hand.", file=sys.stderr)
            return 1
        headers.append(lines)
    if any(lines != headers[0] for lines in headers):
        print("The generated files come from different specs. Regenerate all of them.", file=sys.stderr)
        return 1
    print(f"SDK generator not found at {generator}; checked the generated headers only.")
    print(headers[0][2])
    return 0


if __name__ == "__main__":
    sys.exit(main())
